CREATE TABLE "settings" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_path VARCHAR(255) NOT NULL DEFAULT 'C:\\aasm',
    steamcmd_path VARCHAR(255) NOT NULL DEFAULT 'C:\\steamcmd'
);
