[versions]
kotlin = "2.1.21"
compose = "1.7.3"
composePlugin = "2.1.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composePlugin" }
lumo = { id = "com.nomanr.plugin.lumo", version = "1.2.5" }

