// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['config']['ConfigController']['GetConfig']();
}

export function SaveConfig() {
  return window['go']['config']['ConfigController']['SaveConfig']();
}

export function Startup(arg1) {
  return window['go']['config']['ConfigController']['Startup'](arg1);
}
