// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {context} from '../models';

export function GetAllServers():Promise<{[key: number]: server.Server}|boolean>;

export function GetServer(arg1:number):Promise<server.Server>;

export function SaveServer(arg1:server.Server):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
