// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServer(arg1) {
  return window['go']['server']['ServerController']['GetServer'](arg1);
}

export function SaveServer(arg1) {
  return window['go']['server']['ServerController']['SaveServer'](arg1);
}

export function Startup(arg1) {
  return window['go']['server']['ServerController']['Startup'](arg1);
}
