// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkInterfaces() {
  return window['go']['server']['ServerController']['GetNetworkInterfaces']();
}

export function Startup(arg1) {
  return window['go']['server']['ServerController']['Startup'](arg1);
}
