// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helpers} from '../models';
import {context} from '../models';

export function GetNetworkInterfaces():Promise<Array<helpers.NetworkInterface>>;

export function Startup(arg1:context.Context):Promise<void>;
